### PR TITLE
Remove syntaxes key

### PR DESCRIPTION
**Pull request by rwols**
Please don't merge until https://github.com/sublimelsp/LSP/pull/931 is in the master branch.

### CODE REVIEW

**Comment by predragnikolic** [comment]
I think that I can't merge this PR even after 
https://github.com/sublimelsp/LSP/pull/931

Because sublime.list_syntaxes() is only available on ST4. A lot of people who use this LSP-* plugin still use ST3

**Comment by rwols** [comment]
Yes, that's why I said **master**, not **st4000-exploration**. When **st4000-exploration** is merged into master this can be merged.

**Comment by predragnikolic** [comment]
Unless you meant to wait until we merge the `st exploration 4000` to `master`.
But still before that,
we need to make different package control tags for each LSP-* plugin(one tag for st3 and one for st4). So we don't break them for users who will continue to use st3

**Comment by rchl** [comment]
I will close for now.

**Pull request closed without merging**
