### PR TITLE
Add sublime-package schema

### PR DESCRIPTION
**Pull request by rchl**

### CODE REVIEW

**Comment by rchl** [comment]
Getting this:

Screenshot 2020-11-13 at 10 36 44

We should check whether the suggestion works for us or is that something that requires support in LSP.

**Comment by rchl** [comment]
Also, there is no schema for CSS and JS options as those are technically part of different service that the server uses.

**Comment by rchl** [comment]
> We should check whether the suggestion works for us or is that something that requires support in LSP.

Checked now. This option is dead right now and that future is suported through a custom `html/onTypeRename` [message](https://github.com/vscode-langservers/vscode-html-languageserver/blob/7bb44080b034afe2bc2b3289a199fdba91d69fe3/src/htmlServer.ts#L37).

That means that I will remove this option and not add `editor.renameOnType` as it would do nothing anyway (it's an editor option in VSCode).

**Comment by rchl** [comment]
Also removed "autoClosingTags" settings since it only works properly in tandem with the client sending a custom `html/tag` requests. Without that all that setting this option to `true` does is filtering out the completions for close tags (like `</div>`). And there is no reason to do that.

**Review by predragnikolic — APPROVED** [review]

**Comment by rchl** [comment]
Forgot about this one... :)

> Also, there is no schema for CSS and JS options as those are technically part of different service that the server uses.

So I was wondering if there is a good way to handle that without duplicating schemas but I think I don't see any easy solution.

**Pull request merged**
